[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "confluent-kafka>=2.15.0",
    "email-validator>=2.3.0",
    "fastapi-guard>=7.3.0",
    "fastapi-pagination>=0.15.16",
    "fastapi[standard]>=0.139.0",
    "fpdf2>=2.8.7",
    "httpx>=0.28.1",
    "passlib>=1.7.4",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-ai-slim[ag-ui,openai]>=2.19.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "qrcode[pil]>=8.2",
    "redis>=8.0.1",
    "resend>=2.16.0",
    "ruff>=0.15.22",
    "sqlakeyset>=2.0.1775222100",
    "sqlmodel>=0.0.39",
    "typer>=0.26.8",
]

[dependency-groups]
dev = [
    "pypdf>=6.15.0",
]
