[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "email-validator>=2.3.0",
    "fastapi-guard>=7.3.0",
    "fastapi[standard]>=0.139.0",
    "fpdf2>=2.8.7",
    "httpx>=0.28.1",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "qrcode[pil]>=8.2",
    "redis>=8.0.1",
    "resend>=2.16.0",
    "ruff>=0.15.22",
    "sqlmodel>=0.0.39",
]
