"""make notification timestamps timezone aware

Revision ID: 071347c140e7
Revises: b68c4c938fbf
Create Date: 2026-08-01 01:34:30.109776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "071347c140e7"
down_revision: Union[str, Sequence[str], None] = "b68c4c938fbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerate produced the alter_column calls below with no
    `postgresql_using` - a bare TIMESTAMP -> TIMESTAMPTZ cast interprets
    the existing naive values using the DB session's *current* timezone
    setting, which isn't guaranteed to be UTC. Every row so far was
    written by datetime.utcnow(), so this explicitly casts as UTC rather
    than trusting whatever the session's timezone happens to be - see
    models/notifications.py's utcnow() docstring for the Python side of
    this same change.
    """
    op.alter_column(
        "notification",
        "read_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="read_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "notification",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust (see upgrade()'s
    # docstring - same UTC-explicit reasoning applies in reverse) ###
    op.alter_column(
        "notification",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "notification",
        "read_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="read_at AT TIME ZONE 'UTC'",
    )
    # ### end Alembic commands ###
