"""add fare breakdown, conditions, baggage/cabin to bookings

Revision ID: 3212de09bc79
Revises: d0b5d6488ded
Create Date: 2026-07-28 04:10:12.940402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3212de09bc79"
down_revision: Union[str, Sequence[str], None] = "d0b5d6488ded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("base_amount", sa.String(), nullable=True))
    op.add_column("booking", sa.Column("base_currency", sa.String(), nullable=True))
    op.add_column("booking", sa.Column("tax_amount", sa.String(), nullable=True))
    op.add_column("booking", sa.Column("tax_currency", sa.String(), nullable=True))
    op.add_column("booking", sa.Column("refund_allowed", sa.Boolean(), nullable=True))
    op.add_column(
        "booking", sa.Column("refund_penalty_amount", sa.String(), nullable=True)
    )
    op.add_column(
        "booking", sa.Column("refund_penalty_currency", sa.String(), nullable=True)
    )
    op.add_column("booking", sa.Column("change_allowed", sa.Boolean(), nullable=True))
    op.add_column(
        "booking", sa.Column("change_penalty_amount", sa.String(), nullable=True)
    )
    op.add_column(
        "booking", sa.Column("change_penalty_currency", sa.String(), nullable=True)
    )
    # server_default so existing rows (created before this column existed)
    # get a real value instead of failing the NOT NULL constraint.
    op.add_column(
        "bookingpassenger",
        sa.Column("checked_bags", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "bookingpassenger",
        sa.Column("carry_on_bags", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookingpassenger", "carry_on_bags")
    op.drop_column("bookingpassenger", "checked_bags")
    op.drop_column("booking", "change_penalty_currency")
    op.drop_column("booking", "change_penalty_amount")
    op.drop_column("booking", "change_allowed")
    op.drop_column("booking", "refund_penalty_currency")
    op.drop_column("booking", "refund_penalty_amount")
    op.drop_column("booking", "refund_allowed")
    op.drop_column("booking", "tax_currency")
    op.drop_column("booking", "tax_amount")
    op.drop_column("booking", "base_currency")
    op.drop_column("booking", "base_amount")
    # ### end Alembic commands ###
