"""add google oauth fields to user

Revision ID: 33c6ad5786c4
Revises: 071347c140e7
Create Date: 2026-08-02 04:28:09.037992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33c6ad5786c4"
down_revision: Union[str, Sequence[str], None] = "071347c140e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userindb", sa.Column("oauth_provider", sa.String(), nullable=True))
    op.add_column("userindb", sa.Column("oauth_id", sa.String(), nullable=True))
    op.alter_column("userindb", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(
        op.f("ix_userindb_oauth_id"), "userindb", ["oauth_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_oauth_identity", "userindb", ["oauth_provider", "oauth_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The final alter_column back to NOT NULL will fail once any real
    Google-only account exists (models/users.py's UserInDB.password is
    None for those by design) - there's no value to backfill it with
    that wouldn't be actively wrong, so that's an expected failure mode
    of downgrading past this migration, not a bug in it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_oauth_identity", "userindb", type_="unique")
    op.drop_index(op.f("ix_userindb_oauth_id"), table_name="userindb")
    op.alter_column("userindb", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("userindb", "oauth_id")
    op.drop_column("userindb", "oauth_provider")
    # ### end Alembic commands ###
