"""add flight terminal and operating flight number columns

Revision ID: 63d0ff05ce1f
Revises: de2067dfce59
Create Date: 2026-07-27 22:57:37.742429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63d0ff05ce1f"
down_revision: Union[str, Sequence[str], None] = "de2067dfce59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flight", sa.Column("origin_terminal", sa.String(), nullable=True))
    op.add_column(
        "flight", sa.Column("destination_terminal", sa.String(), nullable=True)
    )
    op.add_column(
        "flight",
        sa.Column("operating_carrier_flight_number", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flight", "operating_carrier_flight_number")
    op.drop_column("flight", "destination_terminal")
    op.drop_column("flight", "origin_terminal")
    # ### end Alembic commands ###
