"""add destinationimage table

Revision ID: 6a006948e84a
Revises: af566a0891c1
Create Date: 2026-07-30 00:48:14.242859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a006948e84a"
down_revision: Union[str, Sequence[str], None] = "af566a0891c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinationimage",
        sa.Column("iata_code", sa.String(), nullable=False),
        sa.Column("unsplash_photo_id", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("thumb_url", sa.String(), nullable=False),
        sa.Column("photographer_name", sa.String(), nullable=False),
        sa.Column("photographer_profile_url", sa.String(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("iata_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("destinationimage")
    # ### end Alembic commands ###
