"""add rbac tables and user staff/superuser flags

Revision ID: ab2552a95776
Revises: f3a06c6fdaf2
Create Date: 2026-07-29 01:10:41.471381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab2552a95776"
down_revision: Union[str, Sequence[str], None] = "f3a06c6fdaf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codename", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_codename"), "permission", ["codename"], unique=True
    )
    op.create_index(
        op.f("ix_permission_content_type"), "permission", ["content_type"], unique=False
    )
    op.create_table(
        "grouppermission",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "permission_id"),
    )
    op.create_table(
        "usergroup",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["userindb.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_table(
        "userpermission",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["userindb.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "permission_id"),
    )
    # server_default so this doesn't fail against existing rows (every
    # UserInDB currently in prod predates these columns) - the app itself
    # never relies on the server default, just Python-side default=False.
    op.add_column(
        "userindb",
        sa.Column("is_staff", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "userindb",
        sa.Column(
            "is_superuser", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userindb", "is_superuser")
    op.drop_column("userindb", "is_staff")
    op.drop_table("userpermission")
    op.drop_table("usergroup")
    op.drop_table("grouppermission")
    op.drop_index(op.f("ix_permission_content_type"), table_name="permission")
    op.drop_index(op.f("ix_permission_codename"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_table("group")
    # ### end Alembic commands ###
