"""add created_at to user

Revision ID: af566a0891c1
Revises: ab2552a95776
Create Date: 2026-07-29 02:36:27.395267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af566a0891c1"
down_revision: Union[str, Sequence[str], None] = "ab2552a95776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this doesn't fail against existing rows (every
    # UserInDB currently in prod predates this column) - exact historical
    # join date isn't recoverable, so existing accounts backfill to "now"
    # at migration time. The app itself never relies on the server
    # default, just Python-side default_factory=datetime.utcnow.
    op.add_column(
        "userindb",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userindb", "created_at")
    # ### end Alembic commands ###
