"""add ban fields to userindb

Revision ID: b0921550f592
Revises: 6a006948e84a
Create Date: 2026-07-30 02:12:59.134688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0921550f592"
down_revision: Union[str, Sequence[str], None] = "6a006948e84a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userindb", sa.Column("banned_at", sa.DateTime(), nullable=True))
    op.add_column("userindb", sa.Column("banned_reason", sa.String(), nullable=True))
    op.add_column("userindb", sa.Column("banned_by_user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "userindb", "userindb", ["banned_by_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userindb", type_="foreignkey")
    op.drop_column("userindb", "banned_by_user_id")
    op.drop_column("userindb", "banned_reason")
    op.drop_column("userindb", "banned_at")
    # ### end Alembic commands ###
