"""add refund table

Revision ID: d2ea7de43750
Revises: 33c6ad5786c4
Create Date: 2026-08-02 17:02:03.093228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2ea7de43750"
down_revision: Union[str, Sequence[str], None] = "33c6ad5786c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refund",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "FAILED",
                "MANUAL_REQUIRED",
                "COMPLETED",
                name="refundstatus",
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("pesapal_confirmation_code", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
        ),
        sa.ForeignKeyConstraint(["payment_id"], ["payment.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refund_booking_id"), "refund", ["booking_id"], unique=False
    )
    op.create_index(op.f("ix_refund_id"), "refund", ["id"], unique=False)
    op.create_index(op.f("ix_refund_payment_id"), "refund", ["payment_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refund_payment_id"), table_name="refund")
    op.drop_index(op.f("ix_refund_id"), table_name="refund")
    op.drop_index(op.f("ix_refund_booking_id"), table_name="refund")
    op.drop_table("refund")
    # ### end Alembic commands ###
