"""baseline

Revision ID: de2067dfce59
Revises:
Create Date: 2026-07-27 22:27:23.556604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de2067dfce59"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `provider` was added to the `payment` table manually (before Alembic
    # existed in this repo) as a plain VARCHAR, unlike every other enum
    # column here (e.g. `status`) which create_all() originally built as a
    # native Postgres enum - SQLAlchemy's Enum type always serializes by
    # the Python enum member's *name* (PESAPAL/DUFFEL), not its .value
    # ("pesapal"/"duffel"), so some rows already hold the by-name-cased
    # default they'll need at the enum column below, and some (through
    # whatever wrote the raw VARCHAR default 'pesapal') don't. Normalize
    # before the ALTER COLUMN, which will otherwise fail outright on the
    # first row whose casing doesn't match an enum label.
    op.execute("UPDATE payment SET provider = UPPER(provider)")
    # Postgres won't auto-cast the column's existing (VARCHAR-typed)
    # default across the type change, so it has to be dropped first and
    # re-added afterwards against the new enum type - alter_column's
    # combined type_=/server_default= wouldn't sequence these correctly.
    op.execute("ALTER TABLE payment ALTER COLUMN provider DROP DEFAULT")
    payment_provider_enum = sa.Enum("PESAPAL", "DUFFEL", name="paymentprovider")
    op.alter_column(
        "payment",
        "provider",
        existing_type=sa.VARCHAR(),
        type_=payment_provider_enum,
        existing_nullable=False,
        postgresql_using="UPPER(provider)::paymentprovider",
    )
    op.execute(
        "ALTER TABLE payment ALTER COLUMN provider SET DEFAULT 'PESAPAL'::paymentprovider"
    )
    op.create_index(
        op.f("ix_payment_duffel_payment_intent_id"),
        "payment",
        ["duffel_payment_intent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_duffel_payment_intent_id"), table_name="payment")
    op.alter_column(
        "payment",
        "provider",
        existing_type=sa.Enum("PESAPAL", "DUFFEL", name="paymentprovider"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        server_default=sa.text("'pesapal'::character varying"),
    )
    # ### end Alembic commands ###
