"""add airline_initiated_change_detected_at to booking

Revision ID: f3a06c6fdaf2
Revises: 3212de09bc79
Create Date: 2026-07-28 04:32:50.477860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3a06c6fdaf2"
down_revision: Union[str, Sequence[str], None] = "3212de09bc79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking",
        sa.Column("airline_initiated_change_detected_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "airline_initiated_change_detected_at")
    # ### end Alembic commands ###
